const SUPABASE_URL = 'https://wmfegtjgfvlnvyepgivd.supabase.co'
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZmVndGpnZnZsbnZ5ZXBnaXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMjg4OTYsImV4cCI6MjA5MjYwNDg5Nn0.ZwEbMCaDcblBrz1-TfINCzJonjmjVh--EXKCk24uQzs'
